#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

printf "\n\360\237\215\272\t Running pre-commit hook...  \n"

printf "\n\360\237\215\272\t Running linter on client...  \n"
yarn lint

printf "\n\360\237\215\272\t Running tests on client...  \n"
yarn test

