name: Test and deploy to prod

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  test:
    uses: theaiscope/GDD-webapp/.github/workflows/test.yaml@v1
  deploy-prod:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node modules
        run: yarn
      - name: Build
        run: yarn build:production
      - name: Deploy client to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P default
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}