name: Test and deploy to test

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy-test:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install node modules
        run: yarn
      - name: Build
        run: yarn build:test
      - name: Deploy client to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy -P test
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TEST }}