name: Test workflow

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: client/package-lock.json
      - name: Install node modules
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test