name: Test client workflow

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  test-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: client/package-lock.json
      - name: Install node modules
        run: |
          cd client
          yarn
      - name: Lint
        run: |
          cd client
          yarn lint
      - name: Test
        run: |
          cd client
          yarn test