name: Test workflow

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install Firebase Emulator Suite
        run: yarn global add firebase-tools
      - name: Install node modules
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
